AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.example.LambdaMethodHandler::handleRequest
      Runtime: java11
      CodeUri: target/lambda-practice-1.0-SNAPSHOT.jar
      Events:
        MyS3Event:
          Type: S3
          Properties:
            Bucket: !Ref test-trigger-lambda-dev-code
            Events: s3:ObjectCreated:*
      Description: Java function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active